# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  project = "joulukalenteri"
  nodes = ["app"]

  id_rsa_ssh_key_pub = File.read(File.join(Dir.home, ".ssh", "id_rsa.pub"))

  nodes.each do |node_name, node_opts|
    config.vm.define node_name do |config|

      config.vm.hostname = "#{project}-#{node_name}"
      config.vm.box = "https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.1.0/centos-7.0-x86_64.box"
      config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

      config.vm.provider "virtualbox" do |v|
        v.gui = false
        v.memory = "512"
        v.name = "#{project}-#{node_name}"
      end

      config.vm.provision :shell, :inline => "echo '#{id_rsa_ssh_key_pub}' >> /home/vagrant/.ssh/authorized_keys && chmod 600 /home/vagrant/.ssh/authorized_keys"

    end
  end

end
